/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Sat Apr 29 19:12:27 2017. */

#include "swakeup.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Location_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Location, country, country, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, Location, city, country, 0),
    PB_LAST_FIELD
};

const pb_field_t Time_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Time, hour, hour, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Time, minute, hour, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, Time, second, minute, 0),
    PB_LAST_FIELD
};

const pb_field_t Date_fields[4] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Date, year, year, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, Date, month, year, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, Date, day, month, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgFrame_fields[7] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, MsgFrame, typ, typ, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, MsgFrame, request, typ, 0),
    PB_ONEOF_FIELD(pl,  16, MESSAGE , ONEOF, STATIC  , OTHER, MsgFrame, location, request, &Location_fields),
    PB_ONEOF_FIELD(pl,  17, MESSAGE , ONEOF, STATIC  , UNION, MsgFrame, time, request, &Time_fields),
    PB_ONEOF_FIELD(pl,  18, MESSAGE , ONEOF, STATIC  , UNION, MsgFrame, date, request, &Date_fields),
    PB_ONEOF_FIELD(pl,  19, ENUM    , ONEOF, STATIC  , UNION, MsgFrame, weather, request, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MsgFrame, pl.location) < 65536 && pb_membersize(MsgFrame, pl.time) < 65536 && pb_membersize(MsgFrame, pl.date) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Location_Time_Date_MsgFrame)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MsgFrame, pl.location) < 256 && pb_membersize(MsgFrame, pl.time) < 256 && pb_membersize(MsgFrame, pl.date) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Location_Time_Date_MsgFrame)
#endif


/* @@protoc_insertion_point(eof) */
