/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Tue May 23 18:39:49 2017. */

#ifndef PB_SWAKEUP_PB_H_INCLUDED
#define PB_SWAKEUP_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MsgType {
    MsgType_MSG_TYPE_NONE = 0,
    MsgType_MSG_TYPE_POWER = 1,
    MsgType_MSG_TYPE_LOCATION = 16,
    MsgType_MSG_TYPE_DATE_TIME = 17,
    MsgType_MSG_TYPE_WEATHER = 18,
    MsgType_MSG_TYPE_SOCIAL = 19,
    MsgType_MSG_TYPE_EMAIL = 20,
    MsgType_MSG_TYPE_ALARM_PUT = 32,
    MsgType_MSG_TYPE_ALARM_GET = 33,
    MsgType_MSG_TYPE_ALARM_REMOVE = 34
} MsgType;
#define _MsgType_MIN MsgType_MSG_TYPE_NONE
#define _MsgType_MAX MsgType_MSG_TYPE_ALARM_REMOVE
#define _MsgType_ARRAYSIZE ((MsgType)(MsgType_MSG_TYPE_ALARM_REMOVE+1))

typedef enum _WeatherType {
    WeatherType_WEATHER_THUNDER = 0,
    WeatherType_WEATHER_SNOW = 1,
    WeatherType_WEATHER_RAIN = 2,
    WeatherType_WEATHER_CLOUDY = 3,
    WeatherType_WEATHER_OVERCAST = 4,
    WeatherType_WEATHER_SUN = 5
} WeatherType;
#define _WeatherType_MIN WeatherType_WEATHER_THUNDER
#define _WeatherType_MAX WeatherType_WEATHER_SUN
#define _WeatherType_ARRAYSIZE ((WeatherType)(WeatherType_WEATHER_SUN+1))

/* Struct definitions */
typedef struct _AlarmGet {
    uint8_t index;
/* @@protoc_insertion_point(struct:AlarmGet) */
} AlarmGet;

typedef struct _AlarmPut {
    uint8_t days;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
/* @@protoc_insertion_point(struct:AlarmPut) */
} AlarmPut;

typedef struct _AlarmRemove {
    uint8_t index;
/* @@protoc_insertion_point(struct:AlarmRemove) */
} AlarmRemove;

typedef struct _DateAndTime {
    uint8_t year;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
/* @@protoc_insertion_point(struct:DateAndTime) */
} DateAndTime;

typedef PB_BYTES_ARRAY_T(5) Email_subject_t;
typedef PB_BYTES_ARRAY_T(5) Email_sender_t;
typedef struct _Email {
    Email_subject_t subject;
    Email_sender_t sender;
/* @@protoc_insertion_point(struct:Email) */
} Email;

typedef struct _Location {
    char country[10];
    char city[10];
/* @@protoc_insertion_point(struct:Location) */
} Location;

typedef PB_BYTES_ARRAY_T(10) Weather_city_t;
typedef struct _Weather {
    WeatherType weatherType;
    uint16_t temperature;
    char unit[1];
    Weather_city_t city;
    uint32_t sunrise;
    uint32_t sunset;
/* @@protoc_insertion_point(struct:Weather) */
} Weather;

typedef struct _MsgFrame {
    MsgType typ;
    bool request;
    Location location;
    pb_size_t which_pl;
    union {
        DateAndTime dateAndTime;
        Weather weather;
        Email email;
        AlarmPut alarmPut;
        AlarmGet alarmGet;
        AlarmRemove alarmRemove;
    } pl;
/* @@protoc_insertion_point(struct:MsgFrame) */
} MsgFrame;

/* Default values for struct fields */

/* Initializer values for message structs */
#define AlarmPut_init_default                    {0, 0, 0, 0}
#define AlarmGet_init_default                    {0}
#define AlarmRemove_init_default                 {0}
#define Email_init_default                       {{0, {0}}, {0, {0}}}
#define Weather_init_default                     {(WeatherType)0, 0, "", {0, {0}}, 0, 0}
#define Location_init_default                    {"", ""}
#define DateAndTime_init_default                 {0, 0, 0, 0, 0, 0}
#define MsgFrame_init_default                    {(MsgType)0, 0, Location_init_default, 0, {DateAndTime_init_default}}
#define AlarmPut_init_zero                       {0, 0, 0, 0}
#define AlarmGet_init_zero                       {0}
#define AlarmRemove_init_zero                    {0}
#define Email_init_zero                          {{0, {0}}, {0, {0}}}
#define Weather_init_zero                        {(WeatherType)0, 0, "", {0, {0}}, 0, 0}
#define Location_init_zero                       {"", ""}
#define DateAndTime_init_zero                    {0, 0, 0, 0, 0, 0}
#define MsgFrame_init_zero                       {(MsgType)0, 0, Location_init_zero, 0, {DateAndTime_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AlarmGet_index_tag                       1
#define AlarmPut_days_tag                        1
#define AlarmPut_hour_tag                        2
#define AlarmPut_minute_tag                      3
#define AlarmPut_second_tag                      4
#define AlarmRemove_index_tag                    1
#define DateAndTime_year_tag                     1
#define DateAndTime_month_tag                    2
#define DateAndTime_day_tag                      3
#define DateAndTime_hour_tag                     4
#define DateAndTime_minute_tag                   5
#define DateAndTime_second_tag                   6
#define Email_subject_tag                        1
#define Email_sender_tag                         2
#define Location_country_tag                     1
#define Location_city_tag                        2
#define Weather_weatherType_tag                  1
#define Weather_temperature_tag                  2
#define Weather_unit_tag                         3
#define Weather_city_tag                         4
#define Weather_sunrise_tag                      5
#define Weather_sunset_tag                       6
#define MsgFrame_dateAndTime_tag                 17
#define MsgFrame_weather_tag                     18
#define MsgFrame_email_tag                       20
#define MsgFrame_alarmPut_tag                    32
#define MsgFrame_alarmGet_tag                    33
#define MsgFrame_alarmRemove_tag                 34
#define MsgFrame_typ_tag                         1
#define MsgFrame_request_tag                     2
#define MsgFrame_location_tag                    3

/* Struct field encoding specification for nanopb */
extern const pb_field_t AlarmPut_fields[5];
extern const pb_field_t AlarmGet_fields[2];
extern const pb_field_t AlarmRemove_fields[2];
extern const pb_field_t Email_fields[3];
extern const pb_field_t Weather_fields[7];
extern const pb_field_t Location_fields[3];
extern const pb_field_t DateAndTime_fields[7];
extern const pb_field_t MsgFrame_fields[10];

/* Maximum encoded size of messages (where known) */
#define AlarmPut_size                            24
#define AlarmGet_size                            6
#define AlarmRemove_size                         6
#define Email_size                               14
#define Weather_size                             35
#define Location_size                            24
#define DateAndTime_size                         36
#define MsgFrame_size                            69

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SWAKEUP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
